name: Web Development Question
description: Ask a question related to Web Development
title: "[Web Development]: "
labels: ["web-dev"]
assignees: "sarvsav"

body:
  - type: textarea
    id: description
    attributes:
      label: Describe your question
      description: |
        1. Clearly explain your question.
        2. Add screenshots if required.
        3. Provide necessary links.
    validations:
      required: true
