name: Philosphy Question
description: Ask a question related to Philosphy
title: "[Philosphy]: "
labels: ["philosphy"]
assignees: "sarvsav"

body:
  - type: textarea
    id: description
    attributes:
      label: Describe your question
      description: |
        1. Clearly explain your question.
        2. Add screenshots if required.
        3. Provide necessary links.
    validations:
      required: true
